version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - static_volume:/app/static
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      - postgres-db
      - redis
      - celery
    env_file:
      - .env
    restart: always
    healthcheck:
      test: curl -f http://127.0.0.1:8000/api/health || exit 1
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s

  postgres-db:
    image: postgres:15-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3

  celery:
    build:
      context: .
    command: celery -A hcs worker --loglevel=info
    depends_on:
      - redis
      - postgres-db
    volumes:
      - .:/app
    networks:
      - app-network
    env_file:
      - .env
    restart: always

  celery-beat:
    build:
      context: .
    command: celery -A hcs beat --loglevel=info
    depends_on:
      - celery
      - redis
      - postgres-db
    volumes:
      - .:/app
    networks:
      - app-network
    env_file:
      - .env
    restart: always
  nginx:
    image: nginx:latest
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/static
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - app

volumes:
  pg_data:
  static_volume:

networks:
  app-network:
    driver: bridge